package com.expensemanager.expense_manager.config;

import com.expensemanager.expense_manager.model.Country;
import com.expensemanager.expense_manager.repository.CountryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class CountryDataSeeder implements CommandLineRunner {

    @Autowired
    private CountryRepository countryRepository;

    @Override
    public void run(String... args) {
        if (countryRepository.count() > 0) return;

        Country[] countries = {
            new Country("Afghanistan", "AF", "AFN", "؋"),
            new Country("Albania", "AL", "ALL", "L"),
            new Country("Algeria", "DZ", "DZD", "د.ج"),
            new Country("Argentina", "AR", "ARS", "$"),
            new Country("Armenia", "AM", "AMD", "֏"),
            new Country("Australia", "AU", "AUD", "A$"),
            new Country("Austria", "AT", "EUR", "€"),
            new Country("Azerbaijan", "AZ", "AZN", "₼"),
            new Country("Bahrain", "BH", "BHD", "BD"),
            new Country("Bangladesh", "BD", "BDT", "৳"),
            new Country("Belarus", "BY", "BYN", "Br"),
            new Country("Belgium", "BE", "EUR", "€"),
            new Country("Bolivia", "BO", "BOB", "Bs"),
            new Country("Bosnia and Herzegovina", "BA", "BAM", "KM"),
            new Country("Brazil", "BR", "BRL", "R$"),
            new Country("Brunei", "BN", "BND", "B$"),
            new Country("Bulgaria", "BG", "BGN", "лв"),
            new Country("Cambodia", "KH", "KHR", "៛"),
            new Country("Cameroon", "CM", "XAF", "FCFA"),
            new Country("Canada", "CA", "CAD", "C$"),
            new Country("Chile", "CL", "CLP", "$"),
            new Country("China", "CN", "CNY", "¥"),
            new Country("Colombia", "CO", "COP", "$"),
            new Country("Costa Rica", "CR", "CRC", "₡"),
            new Country("Croatia", "HR", "EUR", "€"),
            new Country("Cuba", "CU", "CUP", "$"),
            new Country("Cyprus", "CY", "EUR", "€"),
            new Country("Czech Republic", "CZ", "CZK", "Kč"),
            new Country("Denmark", "DK", "DKK", "kr"),
            new Country("Dominican Republic", "DO", "DOP", "RD$"),
            new Country("Ecuador", "EC", "USD", "$"),
            new Country("Egypt", "EG", "EGP", "E£"),
            new Country("El Salvador", "SV", "USD", "$"),
            new Country("Estonia", "EE", "EUR", "€"),
            new Country("Ethiopia", "ET", "ETB", "Br"),
            new Country("Finland", "FI", "EUR", "€"),
            new Country("France", "FR", "EUR", "€"),
            new Country("Georgia", "GE", "GEL", "₾"),
            new Country("Germany", "DE", "EUR", "€"),
            new Country("Ghana", "GH", "GHS", "GH₵"),
            new Country("Greece", "GR", "EUR", "€"),
            new Country("Guatemala", "GT", "GTQ", "Q"),
            new Country("Honduras", "HN", "HNL", "L"),
            new Country("Hong Kong", "HK", "HKD", "HK$"),
            new Country("Hungary", "HU", "HUF", "Ft"),
            new Country("Iceland", "IS", "ISK", "kr"),
            new Country("India", "IN", "INR", "₹"),
            new Country("Indonesia", "ID", "IDR", "Rp"),
            new Country("Iran", "IR", "IRR", "﷼"),
            new Country("Iraq", "IQ", "IQD", "ع.د"),
            new Country("Ireland", "IE", "EUR", "€"),
            new Country("Israel", "IL", "ILS", "₪"),
            new Country("Italy", "IT", "EUR", "€"),
            new Country("Jamaica", "JM", "JMD", "J$"),
            new Country("Japan", "JP", "JPY", "¥"),
            new Country("Jordan", "JO", "JOD", "JD"),
            new Country("Kazakhstan", "KZ", "KZT", "₸"),
            new Country("Kenya", "KE", "KES", "KSh"),
            new Country("Kuwait", "KW", "KWD", "KD"),
            new Country("Kyrgyzstan", "KG", "KGS", "сом"),
            new Country("Laos", "LA", "LAK", "₭"),
            new Country("Latvia", "LV", "EUR", "€"),
            new Country("Lebanon", "LB", "LBP", "L£"),
            new Country("Libya", "LY", "LYD", "LD"),
            new Country("Lithuania", "LT", "EUR", "€"),
            new Country("Luxembourg", "LU", "EUR", "€"),
            new Country("Macau", "MO", "MOP", "MOP$"),
            new Country("Malaysia", "MY", "MYR", "RM"),
            new Country("Maldives", "MV", "MVR", "Rf"),
            new Country("Malta", "MT", "EUR", "€"),
            new Country("Mexico", "MX", "MXN", "MX$"),
            new Country("Moldova", "MD", "MDL", "L"),
            new Country("Mongolia", "MN", "MNT", "₮"),
            new Country("Montenegro", "ME", "EUR", "€"),
            new Country("Morocco", "MA", "MAD", "MAD"),
            new Country("Mozambique", "MZ", "MZN", "MT"),
            new Country("Myanmar", "MM", "MMK", "K"),
            new Country("Nepal", "NP", "NPR", "Rs"),
            new Country("Netherlands", "NL", "EUR", "€"),
            new Country("New Zealand", "NZ", "NZD", "NZ$"),
            new Country("Nicaragua", "NI", "NIO", "C$"),
            new Country("Nigeria", "NG", "NGN", "₦"),
            new Country("North Macedonia", "MK", "MKD", "ден"),
            new Country("Norway", "NO", "NOK", "kr"),
            new Country("Oman", "OM", "OMR", "OMR"),
            new Country("Pakistan", "PK", "PKR", "Rs"),
            new Country("Panama", "PA", "PAB", "B/"),
            new Country("Paraguay", "PY", "PYG", "₲"),
            new Country("Peru", "PE", "PEN", "S/"),
            new Country("Philippines", "PH", "PHP", "₱"),
            new Country("Poland", "PL", "PLN", "zł"),
            new Country("Portugal", "PT", "EUR", "€"),
            new Country("Qatar", "QA", "QAR", "QR"),
            new Country("Romania", "RO", "RON", "lei"),
            new Country("Russia", "RU", "RUB", "₽"),
            new Country("Saudi Arabia", "SA", "SAR", "SAR"),
            new Country("Serbia", "RS", "RSD", "din"),
            new Country("Singapore", "SG", "SGD", "S$"),
            new Country("Slovakia", "SK", "EUR", "€"),
            new Country("Slovenia", "SI", "EUR", "€"),
            new Country("South Africa", "ZA", "ZAR", "R"),
            new Country("South Korea", "KR", "KRW", "₩"),
            new Country("Spain", "ES", "EUR", "€"),
            new Country("Sri Lanka", "LK", "LKR", "Rs"),
            new Country("Sweden", "SE", "SEK", "kr"),
            new Country("Switzerland", "CH", "CHF", "CHF"),
            new Country("Taiwan", "TW", "TWD", "NT$"),
            new Country("Tanzania", "TZ", "TZS", "TSh"),
            new Country("Thailand", "TH", "THB", "฿"),
            new Country("Trinidad and Tobago", "TT", "TTD", "TT$"),
            new Country("Tunisia", "TN", "TND", "DT"),
            new Country("Turkey", "TR", "TRY", "₺"),
            new Country("Uganda", "UG", "UGX", "USh"),
            new Country("Ukraine", "UA", "UAH", "₴"),
            new Country("United Arab Emirates", "AE", "AED", "AED"),
            new Country("United Kingdom", "GB", "GBP", "£"),
            new Country("United States", "US", "USD", "$"),
            new Country("Uruguay", "UY", "UYU", "$U"),
            new Country("Uzbekistan", "UZ", "UZS", "сўм"),
            new Country("Venezuela", "VE", "VES", "Bs"),
            new Country("Vietnam", "VN", "VND", "₫"),
            new Country("Zimbabwe", "ZW", "ZWL", "Z$"),
        };

        for (Country c : countries) {
            countryRepository.save(c);
        }
    }
}
